---
title: 'Confidentiality Check:'
author: ''
date: ' '
output:
  word_document: default
  html_document:
    df_print: paged
  pdf_document: default
---

```{r message = FALSE, warning = FALSE, echo = FALSE, comment=NA, results='asis'} 
# reference:https://anu365.sharepoint.com/:w:/r/sites/CSRM/_layouts/15/Doc.aspx?sourcedoc=%7B87C010D7-F766-474D-B546-BC549834E366%7D&file=Confidentiality%2002%2002%202022.docx&action=default&mobileredirect=true

####################################################################################################
################              Load packages                        #################################
####################################################################################################
library (tidyverse)
library(flextable)          # Creates tables 
library(haven);             # Imports SPSS (.sav) data
library(labelled);          # Calls value label, variable label and other information of the data
library(officer)            # Helps using various micro-soft office formats 
library (spelling)          # For checking spelling error
library (stringr)           # Looking for specific string ('word' or 'parts of word')
library (dplyr)

flexPrintFun <- function(x){
    res <- flextable(x) %>%                        # Forward-pipe operator
    width(j=1, width = 1.0) %>%                    # Set columns width, total 4 columns
    width(j=2, width = 3.0) %>%           
    width(j=3, width = 1.0) %>%
    width(j=4, width = 1.0) %>%
    hrule(rule="auto", part="all") %>%             # hrule(height rule) Set flextable rule for rows heights
    fontsize(part="header", size=11) %>%
    fontsize(part="body", size=10)

}




cat("**Summary report**");cat("\n"); cat("\n")
summ <- data.frame(matrix(rep ('', times = 16,), ncol = 4, byrow = F))               #Create a new empty data frame 4-by-4
colnames (summ) <- c('Section', 'Issue', 'Suggestion', 'Response' )                  #
theme_box(flexPrintFun (summ))
```


```{r message = FALSE, warning = FALSE, echo = FALSE, comment=NA, results='asis'} 
####################################################################################################
################      Read data and get variable information       #################################
####################################################################################################



data <- haven::read_sav("../Data/.sav")

conf_var  <- c( 'p_seifa', 'p_gender', 'p_age_group_ADA', 'd_education')

# conf_var  <- c('dem2a_3','dem2a_2', 'dem2a_1', 'dem9a', 'srcid','pcode','dem5','dem6','A2A','A2B','D4') # Add sus name, customisable global variable, 
                                                                                                        
var_info  <- look_for(data, details = T) %>%                        # extract variable information from spss data
             lookfor_to_long_format() %>%                           # Expand the table by value label, Cartesian product with value label
             convert_list_columns_to_character()                    # Convert list to character for each element in the table

varLabel <- var_label(data)                                         #extract variable label to varLabel
varName  <- unique(var_info$variable)                               #extract variable name

colnames (var_info) <- c("pos", "variable", "label", "col_type", "levels", "value_labels", "class", "type",
                         "na_values",  "na_range", "unique_values", "count_missing", "range")
```



```{r message = FALSE, warning = FALSE, echo = FALSE, comment=NA, results='asis'}  

####################################################################################################
################   Tables with basic information  (Not derived from data) ##########################
####################################################################################################

####################################################################################################
################## Unable to check a part of the variables       ###################################
####################################################################################################
cat("**Detailed report**");cat("\n"); cat("\n")

flexPrintFun <- function(x){                        #Function that print table with 2 columns
  flextable(x) %>%
    width(j=1, width = 1.00) %>%
    width(j=2, width = 2.00) %>%
    hrule(rule="auto", part="all") %>%
    fontsize(part="header", size=8) %>%
    fontsize(part="body", size=8) 
}

missLabel <-  which(varLabel== 'NULL')            # Find the Missing value on variable label.
posi <- as.numeric(missLabel)                     # 
name <- names (missLabel)                         # And extract corresponding variable name 
n <- length (posi)                                # how many label was missing

#if there is a missing variable label, print 
a <- ifelse (n > 0,  'At least one of the variables in the data do not have a variable label. The list of variables with missing variable labels are presented in *Table 1*. Please provide the respective variable labels and check if the variables have any direct or quasi personal identifiable information.', 'All variables in the data have variable label. The check for possible direct or quasi PII is conducted for all variables.');

missLabel_table <- data.frame(matrix (cbind(posi,name), ncol = 2))            # Combine the position and variable name into a missLable_table
colnames (missLabel_table) <- c('Serial',  'Variable name')                   # Assign header(colnames) to missLable_table


cat("\n"); cat("\n")
cat("*Before being released, the datasets should be curated in a way that the individuals could not be identified through the information belong to the data. The information possessing the risk of identifying individuals are called Personally Identifiable Information (PII). This document produces a preliminary report on the existence of any PII in the data.*");cat("\n"); cat("\n")

cat("\n"); cat("\n")
cat("*1.0 Missing variable label*");cat("\n"); cat("\n")
cat("\n"); cat("\n")
cat("The presence of PII in the dataset is checked through an automated process. As a part of the proces, the presence of *key words* is searched in the variable label. If the variable does not have any variable label or have short non-informative labels, automated confidentiality checks cannot be done.");   cat("\n"); cat("\n") 
cat("*1.1 Check for missing variable label*");cat("\n"); cat("\n")
cat("\n"); cat("\n")
cat (a)
cat("\n"); cat("\n")
cat("*Table 1: The list of variables with missing variable labels*")
cat("\n"); cat("\n")
#theme_box(flexPrintFun (missLabel_table))

# theme_box(flexPrintFun(data.frame (sapply( missLabel_table, as.character))))
theme_box(flexPrintFun(convert_list_columns_to_character(missLabel_table) ))

cat("\n"); cat("\n")

```


```{r message = FALSE, warning = FALSE, echo = FALSE, comment=NA, results='asis'}  
####################################################################################################
##################### Direct Personally Identifiable Information ###################################
####################################################################################################
flexPrintFun <- function(x){                  #Function that print table with 6 columns
  flextable(x) %>%
    width(j=1, width = 1.00) %>%
    width(j=2, width = 2.00) %>%
    width(j=3, width = 0.75) %>%
    width(j=4, width = 0.75) %>%
    width(j=5, width = 0.75) %>%
    width(j=6, width = 0.50) %>%
    hrule(rule="auto", part="all") %>%
    fontsize(part="header", size=8) %>%
    fontsize(part="body", size=8) 
}
cat("\n"); cat("\n")

# DPII_keywords <- regex("(iden)|(ID)|(name)|(phone)|(mobile)|(fax)|(URL)|(longi)|(lati)" ,ignore_case=TRUE)                   #Position that varLabel contains ID or name or ....
                          
# var_posi  <- str_which  ( varLabel, DPII_keywords)

# var_match <- str_extract(varLabel[var_posi], DPII_keywords )

var_posi  <- str_which  (varLabel, "(identi)|(ID)|(Name)|(name)|(Phone)|(phone)|(Mobile)|(mobile)", negate = FALSE)
var_match <- str_extract(varLabel[var_posi], "(identi)|(ID)|(Name)|(name)|(Phone)|(phone)|(Mobile)|(mobile)")



                                                                                                      # Potential improvement: Variable name(Rcode): 
                                                                                                      # sl<-> dict_confidential_variable; nv <-> empty_column; 
                                                                                                      # su <-> suggestion_column
dict_var <- paste(var_posi, varName[var_posi], sep = ' :');                                           # Join var_position that contains   
                                                                                                      # Longi or Latitude or url or Url, 
nv_col <- rep('',length(dict_var)); su_col <- rep('KO/ Delete',length(dict_var));                     # Create a empty colom for Response and suggestions

personal_identifiable <- data.frame(matrix (cbind(
              dict_var,varLabel[var_posi],  var_match, su_col, nv_col, nv_col), ncol = 6,))           # Combine all column together. 
colnames (personal_identifiable) <- c('Serial: Name',  'Variable label', 'Match', 'Suggestion', 'Response', 'Status')   # Assign Header of the table

a <- ifelse (length (dict_var) > 0, 'Direct Personally Identifiable Information (DPII) were checked through, the terms, *iden, name, phone, mobile, fax, url, longi* or *lati* in the variable label. The list of variables with Direct Personally Identifiable Information as detected through preliminary search is presented in *Table 2*.', 'Direct Personally Identifiable Information were checked through, the terms, *iden, name, phone, mobile, fax, url, longi* or *lati* in the variable label. No possible Direct Personally Identifiable Information was detected in the preliminary search.');    # Concern: Text should be consistent with var_match if there is any changes or improvements

cat("\n"); cat("\n")
cat("*2.0 Direct Personally Identifiable Information (DPII)*");cat("\n"); cat("\n")
cat("\n"); cat("\n")
cat("The information capable of identifying a person without information from other variable or with cross-linking through other information that is in the public domain. Examples of such identifiers includes, name, telephone number, fax number or email address.")
cat("\n"); cat("\n")
cat("*2.1 Checking DPII in the data*");cat("\n"); cat("\n")
cat (a)
cat("\n"); cat("\n")
cat("*Table 2: List of variables with possible Direct Personally Identifiable Information.*")
cat("\n"); cat("\n")
#theme_box(flexPrintFun (personal_identifiable))

theme_box(flexPrintFun(data.frame (sapply( personal_identifiable, as.character))))                   #print the table

cat("\n"); cat("\n")
cat("*DPII are linked to the highest level of identification risk. DPII in publicly released datasets may be considered as a breach of the law. Please confirm that, this information will only be available in the archival version of the datasets. This information will not be published as a part of any publicly released or restricted release dataset.*");cat("\n"); cat("\n")

```


```{r message = FALSE, warning = FALSE, echo = FALSE, comment=NA, results='asis'}  
####################################################################################################
##################### Indirect Personally Identifiable Information ###################################
####################################################################################################

cat("\n"); cat("\n")
cat("*3.0 Indirect Personally Identifiable Information (IPII)*");cat("\n"); cat("\n")

cat("*The IPII (Quasi or indirect identifiers), by themselves, do not identify a specific individual. However, aggregating with other linked information, they possess the risk of identifying individuals. Examples of such identifiers include, Zip code/Post code, Village/Town, Age, Gender and Education.*"); cat("\n"); cat("\n")

cat("*3.1 Geospatial Indirect Personally Identifiable Information (IPII)*")
cat("\n"); cat("\n")
cat("Geospatial data with units where a small number of population resides may be a potential quasi-identifier. The cut-off point is usually considered as 30 000 individuals. Information on any geographic unit with less than 30 000 individuals may be considered as a potential identifiable risk.");cat("\n"); cat("\n")

IPII_keywords<- regex("(vill)|(town)|(post)|(code)",ignore_case = TRUE)
var_posi<- str_which  (varLabel,IPII_keywords , negate = FALSE)           # possible key word: zip,
var_match <- str_extract (varLabel[var_posi], IPII_keywords) 

dict_var <- paste(var_posi, varName[var_posi], sep = ' :');                                          # Join var_position and varName with ":  "(colon)
nv_col <- rep('',length(dict_var)); su_col <- rep('KO/ Con',length(dict_var));                       # Create a empty colom for Response and suggestions
geographic_identifiable <- data.frame(matrix (cbind(dict_var, varLabel[var_posi], var_match, su_col, nv_col, nv_col), ncol = 6))        # Combine all column together. 
colnames (geographic_identifiable) <- c('Serial: Name', 'Variable label', 'Matches', 'Suggestion', 'Response', 'Status')

a <- ifelse (length (dict_var) > 0,  'Geospatial Indirect Personally Identifiable Information is checked using the terms, *vill, town, post* or *code* in the variable label. A list of possible Geospatial Indirect Personally Identifiable Information as detected through preliminary search is presented in Table 3.', 'Geospatial Indirect Personally Identifiable Information is checked using the terms, *vill, lati, post* or *code* in the variable label. No possible Geospatial Indirect Personally Identifiable Information was detected through preliminary search.');

cat("\n"); cat("\n")
cat (a)
cat("\n"); cat("\n")
cat("*Table 3: List of variables with possible Geospatial Indirect Personally Identifiable Information*")
cat("\n"); cat("\n")
theme_box(flexPrintFun(convert_list_columns_to_character(geographic_identifiable) ))

cat("\n"); cat("\n")
cat("*Geospatial IPII are regarded as a higher level of identification risk in the presence of other quasi identifiers (e.g. age, education, occupation). Geospatial IPII in the publicly released datasets may not be considered as a breach of the law.  This information may not be published as a part of publicly released dataset.*");
cat("\n"); cat("\n")
```




```{r message = FALSE, warning = FALSE, echo = FALSE, comment=NA, results='asis'}  
####################################################################################################
################             Single variable confidentialisation   #################################
####################################################################################################

flexPrintFun <- function(x){                                  #Function to print a table with 5 columns
  flextable(x) %>%
    width(j=1, width = 1.00) %>%
    width(j=2, width = 1.50) %>%
    width(j=3, width = 1.50) %>%
    width(j=4, width = 0.75) %>%
    width(j=5, width = 0.50) %>%
    width(j=6, width = 0.50) %>%
    hrule(rule="auto", part="all") %>%
    fontsize(part="header", size=8) %>%
    fontsize(part="body", size=8) 
}

####################################################################################################
#################   Check variable labels of a set of variables  ###################################
####################################################################################################


cat("\n"); cat("\n")
cat("*3.2 Non-Geospatial IPII:*")
cat("\n"); cat("\n")
cat("\n"); cat("\n")

cat("These Quasi-identifiers, or indirect identifiers, are demographic or other personal or attributes that are not necessarily unique, to an individual. For these variables, at least one of the levels may have low frequency counts, and by linking with other information, they possess the risk of identifying data subjects. For this confidentiality check, initially, the set of possible Quasi-identifiers are chosen and their labels with frequency counts are presented.")

cat("\n"); cat("\n")
cat("\n"); cat("\n")

posi <- c()                                                                    # 
for (i in 1: length (conf_var)) {                                              # For every element in conf_var defined on the top
  posi[i] <- which(unique(var_info$variable) == conf_var[i])                   # Find the position of corresponding element
}                                                                              # 
dict_var <- paste(posi, conf_var, sep = ': ');                                 # Join each #conf_var and conf_var with ":  "(colon)
                                                                               #                 
valueLable <- rep(NA, times = length (conf_var))                               #
for (i in 1: length(conf_var)){
     valueLable[i] <- paste(unlist(subset(var_info, var_info$variable == conf_var[i])$value_labels), collapse ="\n")}  #Extract value label from conf_var
                                                                                                                       #      we defined
nv_col <- rep('',length(dict_var)); su_col <- rep('KO/ Con',length(dict_var))

demographic_identifiable <- data.frame(matrix(cbind(dict_var, varLabel[posi], valueLable, su_col, nv_col, nv_col), ncol = 6))
colnames (demographic_identifiable) <- c('Serial: Name', 'Variable label', 'Value labels', 'Suggestion', 'Response', 'Status')

cat("\n"); cat("\n")
cat(" The table represents a list of variables having at least one *possibly identifiable categories* in the value label. Please check the categories and confirm that, the variable has no identifiable label or suggest possible changes to deal with the issue.") 

cat("\n"); cat("\n")


theme_box(flexPrintFun(convert_list_columns_to_character(demographic_identifiable) ))

# Iussues with the list datatype in the dataframe



```

